Mocking
beyond-the-cloud-dev/query-selector pull request #10
Opened 2023-03-30 19:50 UTC by janeksledziewski

2023-03-31 08:08 UTC, pgajek2 requested changes

2023-03-31 08:08 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    public SOQL setMockingId(String queryIdentifier) {
Ja bym pozostał z `mocking`. Jest takie zgrabniejsze i krótsze

mokuje query o tym id
a
ustaw id mokowania 

```java
  public static List<Account> getPartnerAccounts(String accountName) {
        return AccountSelector.Query
            .field(Account.BillingCity)
            .field(Account.BillingCountry)
            .whereAre(SOQL.FiltersGroup
                .add(SOQL.Filter.field(Account.Name).likeAny(accountName))
                .add(SOQL.Filter.recordType().equal('Partner'))
            )
            .mocking('ExampleController.getPartnerAccounts')
            .asList();
    }
```


```java
  public static List<Account> getPartnerAccounts(String accountName) {
        return AccountSelector.Query
            .field(Account.BillingCity)
            .field(Account.BillingCountry)
            .whereAre(SOQL.FiltersGroup
                .add(SOQL.Filter.field(Account.Name).likeAny(accountName))
                .add(SOQL.Filter.recordType().equal('Partner'))
            )
            .setMockingId('ExampleController.getPartnerAccounts')
            .asList();
    }
```

2023-03-31 08:08 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    private static void setMock(String queryIdentifier, SObjectType sObjectType, String staticResource) {
Tutaj przekazywany jest `SObjectType sObjectType`, a powinniśmy to móc jakoś wyciągnąć później, bo wiemy po `queryIdentifier` co pobiera to query. Tak aby przekazywać tylko 

`setMock(String queryIdentifier, String staticResource)`

2023-03-31 08:08 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +            identifiedMocks.put(queryIdentifier, new List<SObject>());
Olałbym try-catch, jak ktoś debil to trudno, tak musielibyśmy wszystko sprawdzać. Bez try-catch mu sie po prostu test wywali, to juz wystarczająca informacja, że coś zjebał a będzie 1 linijka a nie 6

2023-03-31 08:08 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    private static void setMock(String queryIdentifier, SObjectType sObjectType, String staticResource) {
I jak coś to można by robić `Test.loadData` nie tak od razu, no bo na tym etapie nie masz SObjectType

Moze np. Map<String, String> identifierToStaticResource i do takiej mapy wrzucać a w executorze dopiero robić `Test.loadData`?

2023-03-31 08:08 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +        identifiedMocks.put(queryIdentifier, new List<sObject>{ record });
```java
@TestVisible
private static void setMock(String queryIdentifier, sObject record) {
        setMock(queryIdentifier, new List<sObject>{ record });
}
```

Aby nie duplikowac puta

2023-03-31 20:16 UTC, janeksledziewski commented on force-app/main/default/classes/SOQL.cls
> +    private static void setMock(String queryIdentifier, SObjectType sObjectType, String staticResource) {
Można tak zrobić, ale do tego potrzebujemy dodać kolejną mapę. W tym momencie priorytet ma Id, jeśli query ma id to zwrócimy rekordy z moca id.

I teraz przy kolejnej mapie to się komplikuje, co bierze priorytet? Id, SObject czy StaticResource?

Dopóki jest kontekst statyczny, trudno wyciągnąć co to za SObject, bo samo setMock, z żadnym query nie jest powiązany.

2023-03-31 20:16 UTC, janeksledziewski commented on force-app/main/default/classes/SOQL.cls
> +            identifiedMocks.put(queryIdentifier, new List<SObject>());
To jest zebezpieczenie deploymentu. Jeśli nie ma takiego staticResource dostajemy NullPointer, nie chodzi o samego deva

2023-03-31 20:18 UTC, janeksledziewski commented on force-app/main/default/classes/SOQL.cls
> +    public SOQL setMockingId(String queryIdentifier) {
`.mocking` jest zbyt ogólną nazwą i nie wskazuje, co dokładnie ma być podane. `setMockingId` wydawało się najbardziej zbliżone do celu tej metody.

2023-04-01 15:01 UTC, pgajek2 requested changes

2023-04-01 15:01 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    private static void setMock(sObjectType sObjectType, List<sObject> records) {
I tutaj tez nie jestem pewien, bo dajmy ludziom zbyt dużo możliwości mokowania, jedni będą robić tak, drudzy inaczej

2023-04-01 15:01 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    public SOQL setMockingId(String queryIdentifier) {
Ale setMockingId tez nie mówi do czego to id służy. Tak czy siak trzeba zajrzeć do dokumentacji, albo kodu i przeczytać. 

I jest to tez niespójne z koncepcja nazw innych metod. Mamy krótkie, jednym słowem with, orderBy, offset, etc. Tylko setLimit jest takie.

2023-04-01 15:01 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    private static void setMock(String queryIdentifier, SObjectType sObjectType, String staticResource) {
Gdybyśmy zrobili klasę wewnętrzna to dodatkowa mapa nie będzie żadnym problemem. 

sObjecy w ogóle bym wywalił. Bo to redundancja. Przekazujemy informacje, która już gdzieś tam mamy. 

Możemy wywalić sObject jeśli robić Test.loadTest później. Nie od razu, tylko przy executorze.

2023-04-01 15:01 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +            identifiedMocks.put(queryIdentifier, new List<SObject>());
Ale właśnie. To jest nieoczekiwane zachowanie. Jeśli podaje staticresource to oczekuje ze on będzie a jak nie będzie to powinienem dostać błąd a nie, ze ktoś mi to obsłużył i uzupełnił pusta lista. Musiałbym debugowac później aby do tego dojść.

2023-04-01 15:06 UTC, janeksledziewski commented on force-app/main/default/classes/SOQL.cls
> +    public SOQL setMockingId(String queryIdentifier) {
`.mockId`

2023-04-02 08:23 UTC, pgajek2 requested changes

2023-04-02 08:23 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +        public Mock(){
Nie potrzebujesz contstuktora. Możesz od razu zainicjalizować zmienne.

2023-04-02 08:23 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +        public void setMock(String mockId, SObject record){
Kod jest inaczej sformatowany niż cała reszta:
`public void setMock(String mockId, SObject record) {`

2023-04-02 08:25 UTC, pgajek2 requested changes

2023-04-02 08:25 UTC, pgajek2 commented on force-app/main/default/classes/SOQL.cls
> +    private static Mock mock {
potrzebujesz gettera? 

A samo 
```java
 private static Mock mockInstance = new Mock();
 ```
 by nie wystarczyło?

2023-04-09 13:58 UTC, closed without merging